config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description, :street_address, :city, :state, :zip_code
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index

  end

  def new
    @address = Address.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
def index
  @students = Student.all
end

def new
  @student = Student.new
end

def create
    student = Student.new(student_params)
    if student.save
      flash[:success] = "You created #{student.name}"
      redirect_to students_path
    else
      flash.notice = "Student already exists!"
      redirect_to new_student_path(student)
    end
  end

def show
  @student = Student.find(params[:id])
end

def edit
  @student = Student.find(params[:id])
end

def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      redirect_to student_path
    else
      render :edit
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy

    redirect_to students_path
  end

private

  def student_params
    params.require(:student).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address do |f| %>
  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/addresses/new.html.erb
<h1>Create New Student</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasicChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'Create New Student', new_student_path %>
    <%= link_to 'All Students', students_path %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h2>Edit <%= @student.name %> here!</h2>

<%= render partial: "form" %>

app/views/students/index.html.erb
<h1>All Students</h1>

<ul>
  <% @students.each do |student|  %>
    <li>
      <%= link_to student.name, student_path(student) %>
      <%= link_to "Edit", edit_student_path(student) %>
      <%= link_to "Delete", student_path(student), method: "delete" %>
    </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>Create New Student</h1>
<%= render partial: "form" %>

app/views/students/show.html.erb
<%= @student.name %>


<body>
  <%= link_to 'Create New Address', new_student_address_path(@student) %>
  <%= yield %>
</body>